server:
  port: 80
#spring:
#  zipkin:
#    base-url: http://192.168.206.100:9411/
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      rate: 100

spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: web-all_route
          uri: lb://web-all
          predicates:
            - Host=gmall.com, **.gmall.com
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true #身份标识cookie
