server:
  port: 8004
spring:
  datasource:
    url: jdbc:mysql://192.168.206.100/gmall_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
