server:
  port: 8002
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#  redis:
#    host: 192.168.206.100
#    port: 6379
#    password: Lfy123!@!

app:
  thread-pool:
    core-pool-size: 8
    maximum-pool-size: 24
    keep-alive-time: 5 # min
    work-queue-size: 3000
